app/booking/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from upload.views import image_upload
from calendars.views import signup

urlpatterns = [
    path("", image_upload, name="upload"),
    path("home/", image_upload, name="upload"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
    path("calendars/", include('calendars.urls')),
    path('admin/', admin.site.urls),
]

if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/calendars/urls.py
from django.urls import path
from . import views

app_name = 'calendars'
urlpatterns = [
        path('', views.appointment_list, name='appointment_list'),
        path('appointment/', views.create_appointment, name='create_appointment'),
        path('<int:appointment_id>/', views.details, name='details'),
        ]

app/calendars/models.py
from django.db import models

class Appointment(models.Model):
    title = models.CharField(max_length=200, default='')
    start = models.DateTimeField('date started')
    end = models.DateTimeField('date finished')
    description = models.TextField('description')
    status = models.IntegerField(default=0)
#    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('calendars:detail', args=[self.id])

app/upload/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100)

class Book(models.Model):
    name = models.CharField(max_length=100, blank=False)
    class Meta:
        permissions = (
            ( "read_book", "Can read book"),
            )

app/calendars/forms.py
from django import forms
from django.forms import Textarea
from .models import Appointment

class CreateAppointment(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('title', 'start', 'end', 'description')
        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 20}),
        }

app/calendars/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.contrib.auth import login, authenticate 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .models import Appointment
from .forms import CreateAppointment

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/home/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form })

@login_required(login_url='/login/')
def appointment_list(request):
    latest_appointments = Appointment.objects.order_by('-start')[:5]
    context = {
            'latest_appointments': latest_appointments
    }
    return render(request, 'calendars/index.html', context)

@login_required(login_url='/login/')
def details(request, appointment_id):
    print(appointment_id)
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    return render(request, 'calendars/details.html', {'appointment': appointment})


@login_required(login_url='/login/')
def create_appointment(request):
    if request.method == 'POST':
        form = CreateAppointment(request.POST)
        if form.is_valid():
            form.save()
            return redirect('calendars:appointment_list')
    else:
        form = CreateAppointment()
    return render(request, 'calendars/create_appointment.html', {'form': form})

app/upload/views.py
from django.shortcuts import render,redirect
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm 

@login_required(login_url='/login/')
def image_upload(request):
    if request.method == "POST" and request.FILES["image_file"]:
        image_file = request.FILES["image_file"]
        fs = FileSystemStorage()
        filename = fs.save(image_file.name, image_file)
        image_url = fs.url(filename)
        print(image_url)
        return render(request, "upload.html", {
            "image_url": image_url
            })
    return render(request, "upload.html")

app/calendars/templates/calendars/appointment_form.html
{% block content %}
<h1> Calendar </h1>
<form action="." method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

app/calendars/templates/calendars/create_appointment.html
{% extends 'base.html' %}
{% block content %}
<h1> Calendar </h1>
<form class='site-form' action="{% url 'calendars:create_appointment' %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

app/calendars/templates/calendars/details.html
{% extends 'base.html' %}

<div>
{% block content %}
{{ appointment.title }} 
{{ appointment.description }} 
{{ appointment.start }} 
{{ appointment.end }} 
{% if error_message %} <p><strong> {{ error_message }} </strong></p> {% endif %}

{% endblock %}

</div>

app/calendars/templates/calendars/index.html
{% extends 'base.html' %}

{% block content %}
{% if latest_appointments %}
    <ul>
    {% for appointment in latest_appointments %}
    <li><a href="{% url 'calendars:details' appointment.id %}">{{ appointment.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No appointments are available.</p>
{% endif %}

{% endblock %}

app/calendars/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

app/upload/templates/base.html
<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Web page Wander</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">Calendar app</h1>
      {% block content %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

app/upload/templates/upload.html
{% extends 'base.html' %}

{% block content %}

  <form action="{% url "upload" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image_file">
    <input type="submit" value="submit" />
  </form>

  {% if image_url %}
    <p>File uploaded at: <a href="{{ image_url }}">{{ image_url }}</a></p>
  {% endif %}

{% endblock %}